In [ ]:
#Reading of Datasets
#Checking size,number of null values of in dataset etc....
import pandas as pd
genoData=pd.read_csv("datasets/Genotypic_Data.csv")
phenoData=pd.read_csv("datasets/Phenotypic_Data.csv")
genoData.size
phenoData.size
genoData.head() # display small part of data
phenoData.head()
genoData.info()
phenoData.info()
genoData.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14790 entries, 0 to 14789
Columns: 291 entries, SNPs to WH1142
dtypes: float64(5), int64(1), object(285)
memory usage: 32.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Genotype             280 non-null    object
 1   DH_Dharwad           280 non-null    float64
 2   DH_IARI-DELHI        280 non-null    float64
 3   DH_IARI-Jharkhand    280 non-null    float64
 4   DH_KARNAL            280 non-null    float64
 5   DH_Pooled            280 non-null    float64
 6   GFD_Dharwad          280 non-null    float64
 7   GFD_IARI-Delhi       280 non-null    float64
 8   GFD_IARI-Jharkhand   280 non-null    float64
 9   GFD_Karnal           280 non-null    float64
 10  GFD_Pooled           280 non-null    float64
 11  GNPS_Dharwad         280 non-null    float64
 12  GNPS_IARI-Jharkhand  280 non-null    float64
 13  GNPS_Pooled          280 non-null    float64
 14  GWPS_Dharwad         280 non-null    float64
 15  GWPS_IARI-Delhi      280 non-null    float64
 16  GWPS_IARI-Jharkhand  280 non-null    float64
 17  GWPS_Karnal          280 non-null    float64
 18  GWPS_Ludhiana        280 non-null    float64
 19  GWPS_Pooled          280 non-null    float64
 20  PH_Dharwad           280 non-null    float64
 21  PH_IARI-Delhi        280 non-null    float64
 22  PH_IARI-Jharkhand    280 non-null    float64
 23  PH_Karnal            280 non-null    float64
 24  PH_Ludhiana          280 non-null    float64
 25  PH_Pooled            280 non-null    float64
 26  GY_Dharwad           280 non-null    float64
 27  GY_IARI-Delhi        280 non-null    float64
 28  GY_IARI-JKD          280 non-null    float64
 29  GY_Karnal            280 non-null    float64
 30  GY_Ludhiana          280 non-null    float64
 31  GY_Pooled            280 non-null    float64
dtypes: float64(31), object(1)
memory usage: 70.1+ KB

SNPs          0
alleles       0
Chrom         0
Pos           0
strand        0
           ...
DBW173      379
DBW187      256
MACS6222    265
WH1124      206
WH1142      283
Length: 291, dtype: int64

In [ ]:
#removing the unwated data or columns from the database.
columnsToDrop=['Chrom','Pos','strand','assembly','center','protLSID','assayLSID','panel','QCcode']
genoData=genoData.drop(columnsToDrop,axis=1)
genoData.to_csv("datasets/Updated_Genotype.csv",index=False)
genoData.head()

,SNPs,alleles,AAI-W29,AKAW5080,AKAW5099,BRW3877,CG1029,CG1034,CG1035,CG1036,...,HD3372,HI1655,AKAW5088,MACS6753,DBW330,DBW173,DBW187,MACS6222,WH1124,WH1142
0,AX-94381285,C/T,CC,CC,CC,CC,NaN,TC,CC,CC,...,CC,NaN,CC,CC,TC,CC,CC,TC,CC,TC
1,AX-94383718,A/G,AA,AA,AA,AA,AA,AA,AA,AA,...,AA,AA,AA,AA,AG,AA,AA,AG,AA,AG
2,AX-94384181,A/G,NaN,NaN,AA,AG,GG,AA,NaN,GG,...,AA,GG,AA,AA,GG,GG,AA,AA,GG,GG
3,AX-94384966,T/C,TT,CC,TT,TC,TT,TT,TT,CC,...,TT,TT,CC,TT,CC,TT,TT,TT,TT,CC
4,AX-94386458,C/A,AA,AC,CC,CC,AC,AA,AA,NaN,...,AA,CC,CC,CC,CC,CC,CC,CC,CC,CC

In [ ]:
genoDf=pd.read_csv("/content/datasets/Updated_Genotype.csv")
genoDf.isnull().sum()
# genoDf.head()

SNPs           0
alleles        0
AAI-W29     1155
AKAW5080     624
AKAW5099     616
            ...
DBW173       379
DBW187       256
MACS6222     265
WH1124       206
WH1142       283
Length: 282, dtype: int64

In [ ]:
# replacing null value values with dominating trait nucleiotide.
def replacingnull(value,alleles):
  if pd.isna(value):
    letterbefore=alleles.split("/")[0]
    return letterbefore*2
  else:
    return value

In [ ]:
for column in genoDf.columns[1:]:
    for index, row in genoDf.iterrows():
        genoDf.at[index, column] = replacingnull(row[column], row['alleles'])

genoDf = genoDf.drop(['alleles'], axis=1)

In [ ]:
genoDf.to_csv("/content/datasets/fGenoType.csv",index=False)
genoDf.head

<bound method NDFrame.head of               SNPs AAI-W29 AKAW5080 AKAW5099 BRW3877 CG1029 CG1034 CG1035  \
0      AX-94381285      CC       CC       CC      CC     CC     TC     CC
1      AX-94383718      AA       AA       AA      AA     AA     AA     AA
2      AX-94384181      AA       AA       AA      AG     GG     AA     AA
3      AX-94384966      TT       CC       TT      TC     TT     TT     TT
4      AX-94386458      AA       AC       CC      CC     AC     AA     AA
...            ...     ...      ...      ...     ...    ...    ...    ...
14785  AX-95255434      CC       TT       CC      CC     CC     CC     CC
14786  AX-95257606      AA       AA       AA      AA     AA     AA     AG
14787  AX-95258647      GG       TT       TT      GG     TT     GG     TT
14788  AX-95258998      GG       GG       TG      TT     GG     GG     TG
14789  AX-95259412      CC       TT       CC      CC     CC     TT     TT

      CG1036 CG1037  ... HD3372 HI1655 AKAW5088 MACS6753 DBW330 DBW173 DBW187  \
0         CC     CC  ...     CC     CC       CC       CC     TC     CC     CC
1         AA     AA  ...     AA     AA       AA       AA     AG     AA     AA
2         GG     AG  ...     AA     GG       AA       AA     GG     GG     AA
3         CC     TT  ...     TT     TT       CC       TT     CC     TT     TT
4         CC     AA  ...     AA     CC       CC       CC     CC     CC     CC
...      ...    ...  ...    ...    ...      ...      ...    ...    ...    ...
14785     CC     CC  ...     TC     CC       CC       TC     TC     TC     CC
14786     AA     GG  ...     AA     GG       AA       AA     AA     AA     AA
14787     TT     GG  ...     GG     GG       GG       GG     TT     GG     TT
14788     GG     TG  ...     GG     GG       GG       GG     GG     TG     GG
14789     CC     TT  ...     CC     TT       CC       TT     TT     TT     TT

      MACS6222 WH1124 WH1142
0           TC     CC     TC
1           AG     AA     AG
2           AA     GG     GG
3           TT     TT     CC
4           CC     CC     CC
...        ...    ...    ...
14785       CC     CC     TT
14786       AA     AA     AA
14787       GG     GG     GG
14788       GG     TT     GG
14789       TT     CC     TT

[14790 rows x 281 columns]>

In [ ]:
#training only on pooled data.
dontDrop=['Genotype','DH_Pooled','GFD_Pooled','GNPS_Pooled','GWPS_Pooled','PH_Pooled','GY_Pooled']
phenoData=phenoData[dontDrop]
phenoData.to_csv("/content/datasets/finalphenotype.csv",index=False)
phenoData.head

<bound method NDFrame.head of      Genotype  DH_Pooled  GFD_Pooled  GNPS_Pooled  GWPS_Pooled  PH_Pooled  \
0     AAI-W22     86.794      42.897       77.681        2.880     89.721
1     AAI-W29     87.275      43.136       54.635        2.487    105.657
2    AKAW5080     80.225      44.570       47.878        1.955     98.548
3    AKAW5088     78.530      45.047       44.282        2.144    104.708
4    AKAW5099     76.579      45.286       56.952        2.559     93.936
..        ...        ...         ...          ...          ...        ...
275    WH1279     87.524      43.136       42.786        2.135     97.983
276    WH1280     85.579      42.420       44.910        2.331     94.141
277    WH1281     89.711      41.464       59.003        2.915    105.669
278    WH1283     82.905      44.092       55.576        2.392     99.136
279    WH1284     80.717      44.331       55.962        2.365    103.363

     GY_Pooled
0      314.458
1      377.428
2      381.368
3      392.886
4      423.772
..         ...
275    445.046
276    400.203
277    471.501
278    461.181
279    521.409

[280 rows x 7 columns]>

In [ ]:
#replacing genomic data with numbers
geno_map={'AA':1,'AT':2,'AG':3,'AC':4,'TT':5,'TG':6,'TC':7,'GG':8,'CG':9,'CC':10}
fGenoDf=pd.read_csv("/content/datasets/fGenoType.csv")
for i in fGenoDf[1:]:
  fGenoDf[i]=fGenoDf[i].map(geno_map)
GenoDf=pd.read_csv("/content/datasets/Updated_Genotype.csv")
fGenoDf['SNPs']=GenoDf['SNPs']
fGenoDf.to_csv("/content/datasets/finalGenotype.csv",index=False)

In [ ]:
fGenoDf.head

<bound method NDFrame.head of               SNPs  AAI-W29  AKAW5080  AKAW5099  BRW3877  CG1029  CG1034  \
0      AX-94381285       10        10        10       10      10       7
1      AX-94383718        1         1         1        1       1       1
2      AX-94384181        1         1         1        3       8       1
3      AX-94384966        5        10         5        7       5       5
4      AX-94386458        1         4        10       10       4       1
...            ...      ...       ...       ...      ...     ...     ...
14785  AX-95255434       10         5        10       10      10      10
14786  AX-95257606        1         1         1        1       1       1
14787  AX-95258647        8         5         5        8       5       8
14788  AX-95258998        8         8         6        5       8       8
14789  AX-95259412       10         5        10       10      10       5

       CG1035  CG1036  CG1037  ...  HD3372  HI1655  AKAW5088  MACS6753  \
0          10      10      10  ...      10      10        10        10
1           1       1       1  ...       1       1         1         1
2           1       8       3  ...       1       8         1         1
3           5      10       5  ...       5       5        10         5
4           1      10       1  ...       1      10        10        10
...       ...     ...     ...  ...     ...     ...       ...       ...
14785      10      10      10  ...       7      10        10         7
14786       3       1       8  ...       1       8         1         1
14787       5       5       8  ...       8       8         8         8
14788       6       8       6  ...       8       8         8         8
14789       5      10       5  ...      10       5        10         5

       DBW330  DBW173  DBW187  MACS6222  WH1124  WH1142
0           7      10      10         7      10       7
1           3       1       1         3       1       3
2           8       8       1         1       8       8
3          10       5       5         5       5      10
4          10      10      10        10      10      10
...       ...     ...     ...       ...     ...     ...
14785       7       7      10        10      10       5
14786       1       1       1         1       1       1
14787       5       8       5         8       8       8
14788       8       6       8         8       5       8
14789       5       5       5         5      10       5

[14790 rows x 281 columns]>

In [ ]:
#merging datasets.

fg=pd.read_csv("/content/datasets/finalGenotype.csv")#plant breeds,snps
fp=pd.read_csv("/content/datasets/finalphenotype.csv")#phenotypic traits,plant breeds
#transpose genotype data
fg=fg.set_index('SNPs').T.reset_index()

fg.columns.name=None
fg=fg.rename(columns={'index':'Genotype'})

#merge the final genotype and final phenotype datasets
merged_dataset=pd.merge(fg,fp,on='Genotype')
merged_dataset.to_csv("/content/datasets/merged_dataset.csv",index=False)

In [ ]:
merged_dataset.head
# fg.head

<bound method NDFrame.head of      Genotype  AX-94381285  AX-94383718  AX-94384181  AX-94384966  \
0     AAI-W29           10            1            1            5
1    AKAW5080           10            1            1           10
2    AKAW5099           10            1            1            5
3     BRW3877           10            1            3            7
4      CG1029           10            1            8            5
..        ...          ...          ...          ...          ...
275    DBW173           10            1            8            5
276    DBW187           10            1            1            5
277  MACS6222            7            3            1            5
278    WH1124           10            1            8            5
279    WH1142            7            3            8           10

     AX-94386458  AX-94388999  AX-94389450  AX-94393159  AX-94393655  ...  \
0              1            3           10            1            1  ...
1              4            3           10            1            1  ...
2             10            1            5            8            1  ...
3             10            1            5            1            1  ...
4              4            1            5            1            3  ...
..           ...          ...          ...          ...          ...  ...
275           10            1           10            8            1  ...
276           10            1            5            8            1  ...
277           10            1            5            1            1  ...
278           10            1           10            1            1  ...
279           10            1           10            8            1  ...

     AX-95257606  AX-95258647  AX-95258998  AX-95259412  DH_Pooled  \
0              1            8            8           10     87.275
1              1            5            8            5     80.225
2              1            5            6           10     76.579
3              1            8            5           10     84.358
4              1            5            8           10     81.684
..           ...          ...          ...          ...        ...
275            1            8            6            5     86.794
276            1            5            8            5     82.464
277            1            8            8            5     90.442
278            1            8            5           10     81.540
279            1            8            8            5     85.052

     GFD_Pooled  GNPS_Pooled  GWPS_Pooled  PH_Pooled  GY_Pooled
0        43.136       54.635        2.487    105.657    377.428
1        44.570       47.878        1.955     98.548    381.368
2        45.286       56.952        2.559     93.936    423.772
3        42.897       53.187        2.200    103.351    461.672
4        45.047       35.377        2.167     92.207    424.710
..          ...          ...          ...        ...        ...
275      42.420       59.437        2.398    100.673    478.818
276      44.362       45.776        2.475     98.719    461.657
277      40.267       54.487        2.405     95.316    437.051
278      43.646       45.875        2.095     94.597    409.141
279      43.236       59.132        2.377    100.061    418.770

[280 rows x 14797 columns]>

In [ ]:
md=pd.read_csv("/content/datasets/merged_dataset.csv")
snp_data = md.iloc[:, 0:3530 ]
snp_data

,Genotype,AX-94381285,AX-94383718,AX-94384181,AX-94384966,AX-94386458,AX-94388999,AX-94389450,AX-94393159,AX-94393655,...,AX-95188544,AX-95189279,AX-95189751,AX-95191464,AX-95191873,AX-95196248,AX-95199286,AX-95199865,AX-95201891,AX-95202448
0,AAI-W29,10,1,1,5,1,3,10,1,1,...,8,10,8,10,7,10,8,8,5,5
1,AKAW5080,10,1,1,10,4,3,10,1,1,...,8,10,8,10,10,1,1,8,10,5
2,AKAW5099,10,1,1,5,10,1,5,8,1,...,8,5,8,10,10,10,1,8,10,5
3,BRW3877,10,1,3,7,10,1,5,1,1,...,3,10,8,10,10,10,3,9,10,5
4,CG1029,10,1,8,5,4,1,5,1,3,...,8,5,8,1,10,1,1,8,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,DBW173,10,1,8,5,10,1,10,8,1,...,1,10,8,10,7,10,1,8,5,5
276,DBW187,10,1,1,5,10,1,5,8,1,...,8,10,8,10,7,10,8,8,10,5
277,MACS6222,7,3,1,5,10,1,5,1,1,...,8,10,8,10,10,10,1,9,10,5
278,WH1124,10,1,8,5,10,1,10,1,1,...,8,10,8,10,10,10,8,8,5,1
279,WH1142,7,3,8,10,10,1,10,8,1,...,8,10,8,10,10,10,8,9,10,5

In [ ]:
# Finding the correlation using the snp ratio and/or pooled and finding the number of common snps which highly influence the majority snp
p=[]
f=[]
pooled=['DH_Pooled','GFD_Pooled','GNPS_Pooled','GWPS_Pooled','PH_Pooled','GY_Pooled']
md=pd.read_csv("/content/datasets/merged_dataset.csv")

snp_data = md.iloc[:, 1:3530]

for i in pooled:
    gfd_pooled = md[i]
    corr_gfd = snp_data.corrwith(gfd_pooled)
    snp_corr_df = pd.DataFrame({'SNP': snp_data.columns, 'Correlation':corr_gfd})
    snp_corr_df = snp_corr_df.sort_values(by='Correlation', ascending=False)

    k=[]

    for i,j in enumerate(snp_corr_df['Correlation']):
        if(j>0):
            k.append(snp_corr_df['SNP'].iloc[i])

    # k.sort(reverse=True)
    k = k[0:len(k)*4//5]
    p.append(k)

for i in p:
    print(len(i))
f = p
list1 = f[0]
list2 = f[1]
list3 = f[2]
list4 = f[3]
list5 = f[4]
list6 = f[5]

set1=set(list1)
set2=set(list2)
set3=set(list3)
set4=set(list4)
set5=set(list5)
set6=set(list6)

common_elements=set1.intersection(set2,set3,set4,set5,set6)
common_elements_list=list(common_elements)
print(len(common_elements_list))
'''You may get a different number of SNPs;
I got 24 SNPs for the first time that influence the traits the most.
After running it again, I got 5 SNPs.
It may differ sometimes, so don't worry; that will be fine.
Change the code according to the number of SNPs you got.
I trained using a dataset with 24 SNPs.'''

1419
1435
1389
1393
1493
1368
5

In [ ]:
# Removing the non related snps from the dataset
dp=[]
for i in sorted(md.columns[1:]):
    if i not in common_elements_list:
        dp.append(i)

pooled=['DH_Pooled', 'GFD_Pooled', 'GNPS_Pooled', 'GWPS_Pooled', 'PH_Pooled', 'GY_Pooled']
for i in pooled:
    dp.remove(i)

In [ ]:
# Using the final dataset
md1=pd.read_csv("/content/datasets/merged_dataset.csv")
md1=md1.drop(columns=dp)
md1.to_csv("pheno_geno.csv", index=False)

len(md1['Genotype'])

280

In [ ]:
import pandas as pd
md1=pd.read_csv("/content/pheno_geno.csv")
md1.shape

(280, 12)

# Random Forest

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#without scaling the data
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import pickle

# Load your dataset
df = md1

# x should be the genetic sequences
# y should be the trait values assuming the DNA sequences start from the second column
x = df.iloc[:, 1:25]

# Extract the trait values
y = df[['DH_Pooled', 'GFD_Pooled', 'GNPS_Pooled', 'GWPS_Pooled', 'PH_Pooled', 'GY_Pooled']]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
# Print the highest and lowest values for each trait in the training set
print("Training Set:")
for trait in y.columns:
    max_value_train = y_train[trait].max()
    min_value_train = y_train[trait].min()
    print(f'Trait: {trait}')
    print(f'Highest Value in Training Set: {max_value_train}')
    print(f'Lowest Value in Training Set: {min_value_train}')
    print()

# Print the highest and lowest values for each trait in the test set
print("Test Set:")
for trait in y.columns:
    max_value_test = y_test[trait].max()
    min_value_test = y_test[trait].min()
    print(f'Trait: {trait}')
    print(f'Highest Value in Test Set: {max_value_test}')
    print(f'Lowest Value in Test Set: {min_value_test}')
    print()

# Build and train a random forest regression model
random_forest_model2 = RandomForestRegressor(n_estimators=500, random_state=123)
random_forest_model2.fit(X_train, y_train)
with open('random_forest_model2.pkl', 'wb') as model_file:
    pickle.dump(random_forest_model2, model_file)
y_pred = random_forest_model2.predict(X_test)

# Create an empty list to store RMSE values
rmse_values = []

# Iterate over each trait
traits = ['DH_Pooled', 'GFD_Pooled', 'GNPS_Pooled', 'GWPS_Pooled', 'PH_Pooled', 'GY_Pooled']

for trait in traits:
    trait_index = y.columns.get_loc(trait)

    # Extract actual and predicted values for the current trait
    y_actual_trait = y_test[trait]
    y_pred_trait = y_pred[:, trait_index]

    # Calculate Mean Squared Error for the current trait
    mse_trait = mean_squared_error(y_actual_trait, y_pred_trait)
    rmse_trait = np.sqrt(mse_trait)

    rmse_values.append(rmse_trait)

    print(f'RMSE for {trait}: {rmse_trait}')

# Now you can use the rmse_values list as needed in your analysis.
print(rmse_values)
print(sum(rmse_values) / len(rmse_values))

Training Set:
Trait: DH_Pooled
Highest Value in Training Set: 100.405
Lowest Value in Training Set: 72.694

Trait: GFD_Pooled
Highest Value in Training Set: 46.481
Lowest Value in Training Set: 40.031

Trait: GNPS_Pooled
Highest Value in Training Set: 77.681
Lowest Value in Training Set: 30.454

Trait: GWPS_Pooled
Highest Value in Training Set: 3.876
Lowest Value in Training Set: 1.593

Trait: PH_Pooled
Highest Value in Training Set: 117.684
Lowest Value in Training Set: 84.714

Trait: GY_Pooled
Highest Value in Training Set: 573.497
Lowest Value in Training Set: 275.446

Test Set:
Trait: DH_Pooled
Highest Value in Test Set: 93.115
Lowest Value in Test Set: 77.559

Trait: GFD_Pooled
Highest Value in Test Set: 45.525
Lowest Value in Test Set: 36.686

Trait: GNPS_Pooled
Highest Value in Test Set: 63.058
Lowest Value in Test Set: 31.878

Trait: GWPS_Pooled
Highest Value in Test Set: 2.75
Lowest Value in Test Set: 1.615

Trait: PH_Pooled
Highest Value in Test Set: 107.206
Lowest Value in Test Set: 86.251

Trait: GY_Pooled
Highest Value in Test Set: 523.964
Lowest Value in Test Set: 260.452

RMSE for DH_Pooled: 2.842218792132085
RMSE for GFD_Pooled: 1.1559039589715798
RMSE for GNPS_Pooled: 4.462595437544721
RMSE for GWPS_Pooled: 0.16732561587835657
RMSE for PH_Pooled: 3.2036371288748526
RMSE for GY_Pooled: 7.229064597532472
[2.842218792132085, 1.1559039589715798, 4.462595437544721, 0.16732561587835657, 3.2036371288748526, 7.229064597532472]
3.1767909218223447

In [ ]:
def map_sequence_to_numbers(sequence, geno_map):
    # Check if the sequence length is even
    if len(sequence) % 2 != 0:
        raise ValueError("The sequence length must be even.")

    # Split the sequence into chunks of two characters
    chunks = [sequence[i:i+2] for i in range(0, len(sequence), 2)]

    # Map each chunk to its corresponding number using the geno_map
    mapped_numbers = [geno_map[chunk] for chunk in chunks if chunk in geno_map]

    return mapped_numbers

# Example usage
geno_map = {'AA':1, 'AT':2, 'AG':3, 'AC':4, 'TT':5, 'TG':6, 'TC':7, 'GG':8, 'CG':9, 'CC':10}
sequence = "GGCCGGCCGGTTTGGGGGTTCCGGGGTTGGCCGGGGAGCCCCCCCCCC"  # Example input
mapped_numbers = map_sequence_to_numbers(sequence, geno_map)



# Generate and predict a new sequence
new_sequence_1 = np.array(mapped_numbers).reshape(1, -1)  # Reshape to match input shape
# scaled_new_sequence = scaler_x.transform(new_sequence_1)
predictions = random_forest_model2.predict(new_sequence_1)

# Transform transform the scale of predictions to get the original scale
# predictions = scaler_y.inverse_transform(predictions_scaled)

# print("Root Mean Squared Error (MSE):", rmse)
print(rmse_values)
print("Predictions:", predictions)

[3.5605591658676303, 1.413605456051804, 7.983590391101243, 0.2454097005869274, 4.718618931635337, 53.87099519135265]
Predictions: [[ 82.49901   43.40821   58.821902   2.629304  98.87545  506.091464]]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

# FEED FORWARD NEURAL NETWORK

In [ ]:
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
# Load your dataset
df = md1

# x should be the genetic sequences
# y should be the trait values assuming the DNA sequences start from the second column
x = df.iloc[:, 1:25]

# Extract the trait values
y = df[['DH_Pooled', 'GFD_Pooled', 'GNPS_Pooled', 'GWPS_Pooled', 'PH_Pooled', 'GY_Pooled']]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
# Standardize input features and trait values separately (using the same scalers)
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()
X_train_scaled = scaler_x.fit_transform(X_train)
X_test_scaled = scaler_x.transform(X_test)
y_train_scaled = scaler_y.fit_transform(y_train)
y_test_scaled = scaler_y.transform(y_test)
print("X_train_scaled shape:", X_train_scaled.shape)
print("y_train_scaled shape:", y_train_scaled.shape)

# Define the genotype to number mapping
def create_model(input_shape, num_outputs):
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=input_shape),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(num_outputs)  # Adjust the number of output neurons
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    # optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
    # model.compile(optimizer=optimizer, loss='mean_squared_error')
    return model


num_outputs = y_train.shape[1]
learning_rate = 0.001
batch_size = 32
epochs = 100



num_outputs = y_train.shape[1]

# Create and train the model
model = create_model(input_shape=(24,), num_outputs=num_outputs)
model.fit(X_train_scaled, y_train_scaled,batch_size=batch_size, epochs=epochs, validation_split=0.2, verbose=0)

# # Predict and evaluate
# user_input = input("Enter a sequence of 24 genotypes: ")
# if len(user_input) != 48:
#     print("The input sequence must be exactly 48 characters long (24 genotypes).")
# else:
#     new_sequence = convert_genotypes(user_input)
#     scaled_new_sequence = scaler_x.transform(new_sequence)
#     predictions_scaled = model.predict(scaled_new_sequence)
#     predictions = scaler_y.inverse_transform(predictions_scaled)
#     print("Predictions:", predictions)

#     # Calculate Root Mean Squared Error on test data
#     predictions_test = model.predict(X_test_scaled)
#     rmse = np.sqrt(mean_squared_error(y_test_scaled, predictions_test))
#     print("Root Mean Squared Error (MSE) on Test Data:", rmse)
# Calculate Root Mean Squared Error on test data
predictions_test = model.predict(X_test_scaled)
rmse = np.sqrt(mean_squared_error(y_test_scaled, predictions_test))
print("Root Mean Squared Error (MSE) on Test Data:", rmse)

X_train_scaled shape: (224, 24)
y_train_scaled shape: (224, 6)
2/2 [==============================] - 0s 5ms/step
Root Mean Squared Error (MSE) on Test Data: 0.17893428396236524

In [ ]:
def map_sequence_to_numbers(sequence, geno_map):
    # Check if the sequence length is even
    if len(sequence) != 48:
        raise ValueError("must contain 24 pairs.")

    # # Split the sequence into chunks of two characters
    # chunks = [sequence[i:i+2] for i in range(0, len(sequence), 2)]

    # # Map each chunk to its corresponding number using the geno_map
    # mapped_numbers = [geno_map[chunk] for chunk in chunks if chunk in geno_map]

    # return mapped_numbers
    genotype_list = [sequence[i:i+2] for i in range(0, len(sequence), 2)]
    number_list = [geno_map.get(genotype, 0) for genotype in genotype_list]
    return np.array(number_list).reshape(1, -1)

# Example usage
geno_map = {'AA':1, 'AT':2, 'AG':3, 'AC':4, 'TT':5, 'TG':6, 'TC':7, 'GG':8, 'CG':9, 'CC':10}
sequence = "GGCCGGCCGGTTTGGGGGTTCCGGGGTTGGCCGGGGAGCCCCCCCCCC"  # Example input
new_sequence_1= map_sequence_to_numbers(sequence, geno_map)
# Generate and predict a new sequence
# new_sequence_1 = np.array(mapped_numbers).reshape(1, -1)  # Reshape to match input shape
# scaled_new_sequence = scaler_x.transform(new_sequence_1)
predictions_scaled = random_forest_model2.predict(new_sequence_1)
# predictions = scaler_y.inverse_transform(predictions_scaled)
# print(rmse_values)
print("Predictions:", predictions)

Predictions: [[ 82.49901   43.40821   58.821902   2.629304  98.87545  506.091464]]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


# **FEED FORWARD NEURAL NETWORK (FFNN)**

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

# Define the genotype to number mapping
geno_map = {'AA': 1, 'AT': 2, 'AG': 3, 'AC': 4, 'TT': 5, 'TG': 6, 'TC': 7, 'GG': 8, 'CG': 9, 'CC': 10}

# Function to convert genotype sequence to numerical format
def convert_genotypes(sequence):
    genotype_list = [sequence[i:i+2] for i in range(0, len(sequence), 2)]
    number_list = [geno_map.get(genotype, 0) for genotype in genotype_list]
    return np.array(number_list).reshape(1, -1)

def create_model(input_shape, num_outputs):
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=input_shape),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(num_outputs)  # Adjust the number of output neurons
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

num_outputs = y_train.shape[1]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()
X_train_scaled = scaler_x.fit_transform(X_train)
X_test_scaled = scaler_x.transform(X_test)
y_train_scaled = scaler_y.fit_transform(y_train)
y_test_scaled = scaler_y.transform(y_test)

learning_rate = 0.001
batch_size = 32
epochs = 100

print("X_train_scaled shape:", X_train_scaled.shape)
print("y_train_scaled shape:", y_train_scaled.shape)

# Define early stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

# Create and train the model with early stopping
model = create_model(input_shape=(24,), num_outputs=num_outputs)
history = model.fit(X_train_scaled, y_train_scaled, epochs=300, batch_size=batch_size,
                    validation_split=0.2, callbacks=[early_stopping])
print("number of epochs ran:",len(history.history['loss']))
# Predict and evaluate
user_input ="GGCCGGCCGGTTTGGGGGTTCCGGGGTTGGCCGGGGAGCCCCCCCCCC"
new_sequence = convert_genotypes(user_input)
scaled_new_sequence = scaler_x.transform(new_sequence)
predictions_scaled = model.predict(scaled_new_sequence)
print("Predictions_scaled:", predictions_scaled)
predictions = scaler_y.inverse_transform(predictions_scaled)
print("Predictions:", predictions)

# Calculate Root Mean Squared Error on test data
predictions_test = model.predict(X_test_scaled)
rmse = np.sqrt(mean_squared_error(y_test_scaled, predictions_test))
print("Root Mean Squared Error (MSE) on Test Data:", rmse)

X_train_scaled shape: (224, 24)
y_train_scaled shape: (224, 6)
Epoch 1/300
6/6 [==============================] - 1s 34ms/step - loss: 0.3494 - val_loss: 0.1765
Epoch 2/300
6/6 [==============================] - 0s 8ms/step - loss: 0.1418 - val_loss: 0.1000
Epoch 3/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0860 - val_loss: 0.0766
Epoch 4/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0652 - val_loss: 0.0636
Epoch 5/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0573 - val_loss: 0.0554
Epoch 6/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0520 - val_loss: 0.0507
Epoch 7/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0484 - val_loss: 0.0473
Epoch 8/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0439 - val_loss: 0.0438
Epoch 9/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0405 - val_loss: 0.0420
Epoch 10/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0383 - val_loss: 0.0398
Epoch 11/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0363 - val_loss: 0.0378
Epoch 12/300
6/6 [==============================] - 0s 14ms/step - loss: 0.0346 - val_loss: 0.0364
Epoch 13/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0333 - val_loss: 0.0353
Epoch 14/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0321 - val_loss: 0.0345
Epoch 15/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0312 - val_loss: 0.0337
Epoch 16/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0303 - val_loss: 0.0326
Epoch 17/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0294 - val_loss: 0.0319
Epoch 18/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0285 - val_loss: 0.0310
Epoch 19/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0279 - val_loss: 0.0310
Epoch 20/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0273 - val_loss: 0.0307
Epoch 21/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0267 - val_loss: 0.0296
Epoch 22/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0261 - val_loss: 0.0293
Epoch 23/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0257 - val_loss: 0.0294
Epoch 24/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0252 - val_loss: 0.0291
Epoch 25/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0249 - val_loss: 0.0290
Epoch 26/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0244 - val_loss: 0.0291
Epoch 27/300
6/6 [==============================] - 0s 10ms/step - loss: 0.0243 - val_loss: 0.0287
Epoch 28/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0238 - val_loss: 0.0291
Epoch 29/300
6/6 [==============================] - 0s 11ms/step - loss: 0.0235 - val_loss: 0.0287
Epoch 30/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0233 - val_loss: 0.0287
Epoch 31/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0230 - val_loss: 0.0285
Epoch 32/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0227 - val_loss: 0.0285
Epoch 33/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0225 - val_loss: 0.0284
Epoch 34/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0224 - val_loss: 0.0286
Epoch 35/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0221 - val_loss: 0.0285
Epoch 36/300
6/6 [==============================] - 0s 10ms/step - loss: 0.0219 - val_loss: 0.0285
Epoch 37/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0218 - val_loss: 0.0281
Epoch 38/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0216 - val_loss: 0.0287
Epoch 39/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0219 - val_loss: 0.0283
Epoch 40/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0212 - val_loss: 0.0285
Epoch 41/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0212 - val_loss: 0.0285
Epoch 42/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0210 - val_loss: 0.0283
Epoch 43/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0209 - val_loss: 0.0285
Epoch 44/300
6/6 [==============================] - 0s 9ms/step - loss: 0.0208 - val_loss: 0.0282
Epoch 45/300
6/6 [==============================] - 0s 11ms/step - loss: 0.0206 - val_loss: 0.0287
Epoch 46/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0205 - val_loss: 0.0284
Epoch 47/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0204 - val_loss: 0.0283
Epoch 48/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0203 - val_loss: 0.0284
Epoch 49/300
6/6 [==============================] - 0s 8ms/step - loss: 0.0201 - val_loss: 0.0285
Epoch 50/300
6/6 [==============================] - 0s 12ms/step - loss: 0.0200 - val_loss: 0.0286
Epoch 51/300
6/6 [==============================] - 0s 16ms/step - loss: 0.0199 - val_loss: 0.0282
Epoch 52/300
6/6 [==============================] - 0s 15ms/step - loss: 0.0199 - val_loss: 0.0283
Epoch 53/300
6/6 [==============================] - 0s 17ms/step - loss: 0.0198 - val_loss: 0.0281
Epoch 54/300
6/6 [==============================] - 0s 17ms/step - loss: 0.0196 - val_loss: 0.0282
Epoch 55/300
6/6 [==============================] - 0s 13ms/step - loss: 0.0195 - val_loss: 0.0283
Epoch 56/300
6/6 [==============================] - 0s 15ms/step - loss: 0.0193 - val_loss: 0.0282
Epoch 57/300
6/6 [==============================] - 0s 16ms/step - loss: 0.0194 - val_loss: 0.0283
number of epochs ran: 57
1/1 [==============================] - 0s 87ms/step
Predictions_scaled:

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

[[0.45631245 0.549853   0.5576384  0.4138391  0.44613165 0.5813649 ]]
Predictions: [[ 85.338875   43.577553   56.78959     2.5377946  99.422966  448.7224   ]]
2/2 [==============================] - 0s 5ms/step
Root Mean Squared Error (MSE) on Test Data: 0.1723364120783049

In [ ]:
# with open('FFNN.pkl', 'wb') as model_file:
#     pickle.dump(model, model_file)
model.save("FFNN.h5")
with open('scaler_y.pkl', 'wb') as file:
    pickle.dump(scaler_y, file)
with open('scaler_x.pkl', 'wb') as file:
    pickle.dump(scaler_x, file)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(